// Code generated by MockGen. DO NOT EDIT.
// Source: ./net.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	interfaces "github.com/PierreKieffer/pitop/interfaces"
	gomock "github.com/golang/mock/gomock"
)

// MockNetInfo is a mock of NetInfo interface.
type MockNetInfo struct {
	ctrl     *gomock.Controller
	recorder *MockNetInfoMockRecorder
}

// MockNetInfoMockRecorder is the mock recorder for MockNetInfo.
type MockNetInfoMockRecorder struct {
	mock *MockNetInfo
}

// NewMockNetInfo creates a new mock instance.
func NewMockNetInfo(ctrl *gomock.Controller) *MockNetInfo {
	mock := &MockNetInfo{ctrl: ctrl}
	mock.recorder = &MockNetInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetInfo) EXPECT() *MockNetInfoMockRecorder {
	return m.recorder
}

// ComputeNetStats mocks base method.
func (m *MockNetInfo) ComputeNetStats() *interfaces.NetStat {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComputeNetStats")
	ret0, _ := ret[0].(*interfaces.NetStat)
	return ret0
}

// ComputeNetStats indicates an expected call of ComputeNetStats.
func (mr *MockNetInfoMockRecorder) ComputeNetStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComputeNetStats", reflect.TypeOf((*MockNetInfo)(nil).ComputeNetStats))
}
